### ISSUE TITLE
No password required?

### ISSUE THREAD

**Issue by KateLibC** [0xPoly/Centry#1]
I noticed that there is no mention of authentication anywhere in this. What steps have you or are you going to take to prevent this from being triggered by someone not of your own?

**Comment by katanacrimson** [comment]
According to a comment posted on the /r/netsec thread, ~~a port scan for :80 on the device can also result in a panic and wipe~~ it will immediately panic on startup.

Kind of a small problem there.

**Comment by 0xPoly** [comment]
Thanks for the feedback. I was considering taking a inputing a password as a SHA-256 sum and using the hash for authentication. I'll begin working on it soon.

**Comment by 0xPoly** [comment]
Fixed. I've disabled the TCP features until I can think of a better implementation. I've added UDP authentication for the broadcast panics. You'll just need to run "./centry password" instead.
